_wandb:
    value:
        cli_version: 0.21.4
        e:
            nco8it16hb6aw5dzw5tnm93ivnl3qbvw:
                args:
                    - --config
                    - configs/baselineRNN.yaml
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "982820896768"
                        used: "537516720128"
                email: camartinbu@gmail.com
                executable: /home/mmeza/anaconda3/envs/prosody/bin/python
                git:
                    commit: d60844913a0870534c89838a65a48fa19509c55d
                    remote: git@github.com:martinBmeza/punctcapBERT.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-35708f34-ddfd-978a-a032-d49789d185d8
                host: mate
                memory:
                    total: "33439940608"
                os: Linux-6.8.0-87-generic-x86_64-with-glibc2.35
                program: /home/mmeza/punctcapBERT/train.py
                python: CPython 3.9.12
                root: /home/mmeza/punctcapBERT
                startedAt: "2025-11-28T11:33:29.449815Z"
                writerId: nco8it16hb6aw5dzw5tnm93ivnl3qbvw
        m: []
        python_version: 3.9.12
        t:
            "1":
                - 1
                - 11
                - 49
            "2":
                - 1
                - 11
                - 49
            "3":
                - 2
                - 15
                - 16
            "4": 3.9.12
            "5": 0.21.4
            "6": 4.50.3
            "12": 0.21.4
            "13": linux-x86_64
batch_size:
    value: 32
device:
    value: cuda
embed_dim:
    value: 768
epochs:
    value: 100
hidden_dim:
    value: 256
lr:
    value: 0.001
max_examples:
    value: 5
metadata:
    value: data/processed/wikipedia/metadata_train.parquet
out_dir:
    value: results/
store_checkpoints:
    value: false
use_wandb:
    value: true
wandb_notes:
    value: Baseline RNN model with pre-computed BERT embeddings
wandb_project:
    value: punctcapBERT
wandb_run_name:
    value: null
wandb_tags:
    value:
        - baseline
        - rnn
        - bert-embeddings
